[iOS] Adds a missing header import to BATBraveAds+Private.h.
Compilation error:

 In file included from ../../brave/vendor/brave-ios/Ads/BATBraveAds.mm:8:
 ../../brave/vendor/brave-ios/Ads/BATBraveAds+Private.h:5:12: error: cannot find interface declaration for 'BATBraveAds'
 @interface BATBraveAds (Private)